// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import UserProfileController from "./user_profile_controller"
application.register("user-profile", UserProfileController)

// import SelectController from "./select_controller"
// application.register('select', SelectController)

import { Alert, Autosave, Dropdown, Modal, Tabs, Popover, Toggle, Slideover } from "tailwindcss-stimulus-components"
application.register('alert', Alert)
application.register('autosave', Autosave)
application.register('dropdown', Dropdown)
application.register('modal', Modal)
application.register('tabs', Tabs)
application.register('popover', Popover)
application.register('toggle', Toggle)
application.register('slideover', Slideover)

import StimulusSlimselect from "./stimulus_slimselect_controller"
application.register('select2', StimulusSlimselect)

import ModalController from "./modal_controller";
application.register('modal2', ModalController)

import CostumeAlert from "./costume_alert_controller";
application.register('alert2', CostumeAlert)

import SearchController from "./search_controller";
application.register('search', SearchController)

import ExportCvsController from "./export_cvs_controller";
application.register('csv', ExportCvsController)

import DatatablesController from "./datatables_controller";
application.register('datatable', DatatablesController)

import RoleController from "./role_controller";
application.register('role', RoleController)



